config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: redirect('/services')

  resources :users, only: [:index, :new, :create, :destroy]
  resources :machines

  resources :storage_providers do
    collection do
      get :choose
    end
  end

  resources :services do
    resources :backups, only: [:create]

    collection do
      get :choose
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord

  DEFAULT_SERVICE_TYPE = 'redis'
  SERVICES = {
    redis: [
      'containerdb/redis:3.2.9-alpine',
    ],
    postgres: [
      'postgres:9.6.3',
      'postgres:9.6.3-alpine',
      'postgres:5.5.7',
      'postgres:5.5.7-alpine',
      'postgres:5.4.12',
      'postgres:5.4.12-alpine',
      'postgres:5.3.17',
      'postgres:5.3.17-alpine',
      'postgres:5.2.21',
      'postgres:5.2.21-alpine',
    ],
    mysql: [
      'mysql:5.7.18',
      'mysql:8.0.1',
      'mysql:5.6.36',
      'mysql:5.5.56',
    ],
    memsql: [
      'memsql/quickstart:6.0.13'
    ],
    elasticsearch: [
      'docker.elastic.co/elasticsearch/elasticsearch-platinum:6.1.2'
    ]
  }

  validates :name, presence: true
  validates :machine, presence: true

  validates :port, presence: true
  validates :port, uniqueness: { scope: [:machine, :hosted] }, if: :hosted?

  validates :backup_storage_provider, presence: true, allow_nil: true

  validates :service_type, presence: true, inclusion: { in: Service::SERVICES.keys.map(&:to_s) }
  validate :validate_environment_variables
  validate :validate_image, if: :hosted?

  after_initialize :assign_default_service_type
  after_initialize :assign_port, if: :hosted?
  after_initialize :assign_environment_variables

  before_destroy :destroy_container, if: :hosted?

  has_many :backups
  belongs_to :backup_storage_provider, class_name: 'StorageProvider', optional: true
  belongs_to :machine

  def backup(inline: false)
    if inline
      BackupWorker.new.perform(self.backups.create.id)
    else
      BackupWorker.perform_async(self.backups.create.id)
    end
  end

  def container
    Docker::Container.get(container_id, machine.docker) if container_id
  end

  def destroy_container
    if container_id.present?
      container.kill!
      container.delete
    end
  rescue Docker::Error::NotFoundError
    nil
  end

  def default_environment_variables
    variables = service.default_environment_variables

    # If this is an external service, we dont want any default variable assignments
    # We also want to be able to porvide a host
    unless hosted?
      variables.merge!('HOST' => nil)
      variables.each { |k, v| variables[k] = nil }
    end

    variables
  end

  def required_environment_variables
    variables = service.required_environment_variables
    variables += ['HOST'] unless hosted?
    variables
  end

  def connection_string
    service.connection_string
  end

  def connection_command
    service.connection_command
  end

  def backup_environment_variables
    service.backup_environment_variables
  end

  def backup_script_path
    service.backup_script_path
  end

  def backup_file_name
    service.backup_file_name
  end

  def host
    environment_variables['HOST'] || machine.hostname
  end

  def can_backup?
    backup_environment_variables.present? && backup_storage_provider.present?
  rescue NotImplementedError
    false
  end

  def container_env
    self.environment_variables.map do |key, value|
      "#{key}=#{value}"
    end
  end

  def service
    @_service ||= "Service::#{service_type.capitalize}Service".constantize.new(self)
  end

  def available_images
    Service::SERVICES[service_type.to_sym]
  end

  def external?
    !hosted?
  end

  protected

  def assign_default_service_type
    self.service_type ||= DEFAULT_SERVICE_TYPE
  end

  # @todo handle collisions
  def assign_port
    self.port ||= (rand(65000 - 1024) + 1024)
  end

  def assign_environment_variables
    self.environment_variables = default_environment_variables.merge(self.environment_variables)
  end

  def validate_environment_variables
    required_environment_variables.each do |variable|
      errors.add(:environment_variable, "\"#{variable}\" is required") unless environment_variables[variable].present?
    end
  end

  def validate_image
    if image.nil? || !available_images.include?(image)
      errors.add(:image, "is invalid. Must be #{available_images.join('or ')} ")
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.eager_load(:backup_storage_provider, :machine).order(created_at: :desc)
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy unless @service.locked?
    redirect_to root_path
  end

  def new
    return redirect_to choose_services_path unless params[:service].present?
    ensure_machine! if params[:hosted]

    @service = Service.new(service_type: params[:service], hosted: params[:hosted])
  end

  def create
    @service = Service.new(create_params)
    if @service.save
      StartServiceWorker.perform_async(@service.id) if @service.hosted?
      redirect_to services_path
    else
      render :new
    end
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(update_params)
      redirect_to edit_service_path(@service)
    else
      render :edit
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  private

  def ensure_machine!
    unless Machine.any?
      flash[:info] = 'Before you can create a hosted Service, you must create a Machine.'
      redirect_to new_machine_path
    end
  end

  def update_params
    params.require(:service).permit(:name, :backup_storage_provider_id)
  end

  def create_params
    params.require(:service).permit(
      :service_type, :name, :hosted, :image,
      :port, :backup_storage_provider_id, :machine_id,
      environment_variables: service_env_keys,
    )
  end

  def service_env_keys
    # Create a temp service so that we can get the default environment variable keys.
    # @todo there will be a cleaner way to do this
    Service.new(params.require(:service).permit(:service_type, :hosted)).default_environment_variables.keys
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_connect.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", :id => "connection-#{service.id}", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
          Connection Details for #{service.name}
      .modal-body
        = simple_form_for service do |f|
          = f.input :connection_command, readonly: true
          = f.input :connection_string, readonly: true

app/views/services/_form.html.haml
= render 'connect', service: @service if @service.persisted?

= simple_form_for @service do |f|

  = f.error_notification message: (f.object.errors.full_messages.join("<br />") )

  = f.input :name
  = f.input :backup_storage_provider_id, collection: StorageProvider.all, label: 'Backup Storage Provider', label_method: :label_method

  - if @service.new_record?
    = f.input :machine_id, collection: Machine.all, include_blank: false
    = f.input :hosted, as: :hidden
    = f.input :service_type, as: :hidden
    = f.input :image, collection: @service.available_images, include_blank: false, label: 'Image/Version'
    = f.input :port

    %h1.lead Environment Variables
    - environment_variables = ::EnvironmentVariablesDecorator.new(@service.default_environment_variables.merge(@service.environment_variables))
    = f.simple_fields_for(environment_variables) do |field|
      - environment_variables.each do |key, value|
        = field.input key, label: key.to_s

  = f.button :submit, 'Save'
  - if @service.persisted?
    - unless @service.locked?
      = link_to (@service.hosted? ? 'Destroy' : 'Remove'), service_path(@service), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }

    - if (@service.hosted? && @service.container_id.present?) || @service.external?
      %button.btn.btn-primary{"data-target" => "#connection-#{@service.id}", "data-toggle" => "modal", :type => "button"} Connect

app/views/services/_table.html.haml
- if services.any?
  %table.table.table-striped
    %tr
      %th Service
      %th Machine
      %th Type
      %th Image
      %th Container
      %th Port
      %th Backup Provider
      %th Connect
    - services.each do |service|
      = render 'services/connect', service: service
      %tr
        %td= link_to service.name, edit_service_path(service)
        %td= link_to (service.machine.try(:name) || '-'), edit_machine_path(service.machine)
        %td= service.service_type
        %td
          %em.text-muted
            = service.hosted? ? service.image : "external"
        %td
          - if service.hosted?
            - if service.container_id
              %samp= service.container_id.to_s.first(12)
            - else
              %em.text-muted starting..
          - else
            %em.text-muted n/a
        %td= service.port
        %td
          - if service.backup_storage_provider_id.present?
            %em.text-muted [#{service.backup_storage_provider.provider}]
            #{service.backup_storage_provider.name}
          - else
            = "-"
        %td
          - if (service.hosted? && service.container_id.present?) || service.external?
            %button.btn.btn-primary.btn-xs{"data-target" => "#connection-#{service.id}", "data-toggle" => "modal", :type => "button"} Connect
          - else
            = '-'

- else
  %p.alert.alert-info You have not launched any services yet

app/views/services/choose.haml
= content_for :title, 'Choose a Service'

%h1.lead Choose a Service

%table.table.table-striped.well
  %tr
    %th Service
    %th Location
  - Service::SERVICES.each do |service, images|
    %tr
      %td= service
      %td
        = link_to 'Hosted', new_service_path(service: service, hosted: true), class: 'btn btn-xs btn-primary'
        = link_to 'External', new_service_path(service: service, hosted: false), class: 'btn btn-xs btn-primary'

app/views/services/edit.html.haml
= content_for :title, "Edit #{@service.name}"

.row
  .col-md-3
    %h1.lead= @service.name
    = render 'form'
  .col-md-9

    %h1.lead
      Backups
      - if @service.can_backup?
        .pull-right
          = link_to '+', service_backups_path(@service), method: :create, class: 'btn btn-success'

    - if @service.backups.any?
      %table.table.table-striped
        %tr
          %th Time
          %th File Name
          %th Status
        - @service.backups.order(created_at: :desc).each do |backup|
          %tr
            %td= backup.created_at
            %td= backup.file_name || '-'
            %td= backup.status
    - else
      %p.alert.alert-info You have no backups yet!

app/views/services/index.haml
%h1.lead
  Services
  .pull-right
    = link_to '+', choose_services_path, class: 'btn btn-success'

= render 'table', services: @services

app/views/services/new.haml
= content_for :title, "Create a #{@service.service_type.to_s.titleize} Service"

%h1.lead Create a #{@service.service_type.to_s.titleize} Service

- if @service.service.publicly_accessible
  %p.alert.alert-danger Warning: This service will be publicly accessible without any authentication. Please secure it with a firewall.

= render 'form'