config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: redirect('/services')

  resources :users, only: [:index, :new, :create, :destroy]
  resources :machines

  resources :storage_providers do
    collection do
      get :choose
    end
  end

  resources :services do
    resources :backups, only: [:create]

    collection do
      get :choose
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.order(created_at: :desc)
  end

  def create
    @user = User.new(create_params)
    if @user.save
      flash[:info] = "#{@user.email} has been created with the password of #{create_params[:password]}"
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :back
  end

  private

  def create_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/users/_form.html.haml
= simple_form_for @user do |u|
  = u.input :email
  = u.input :password, input_html: { value: SecureRandom.hex.first(12) }, as: :string
  = u.button :submit

app/views/users/index.html.haml
%h1.lead
  Users
  .pull-right
    = link_to '+', new_user_path, class: 'btn btn-success'

%table.table.table-striped
  %tr
    %th Email
    %th Signed Up
    %th Last Sign In
    %th Remove
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.created_at.strftime('%Y-%m-%d %H:%M')
      %td= user.last_sign_in_at.try(:strftime, '%Y-%m-%d %H:%M') || '-'
      %td= link_to 'Remove', user_path(user), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?' }

app/views/users/new.html.haml
= content_for :title, "Invite a User"
%h1.lead Invite a User

= render 'form'