config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: redirect('/services')

  resources :users, only: [:index, :new, :create, :destroy]
  resources :machines

  resources :storage_providers do
    collection do
      get :choose
    end
  end

  resources :services do
    resources :backups, only: [:create]

    collection do
      get :choose
    end
  end
end

app/models/storage_provider.rb
class StorageProvider < ApplicationRecord

  PROVIDERS = ['s3', 'local']

  validates :name, presence: true
  validates :provider, presence: true, inclusion: { in: PROVIDERS }
  validate :validate_environment_variables

  def label_method
    "[#{provider}] #{name}"
  end

  def storage_provider_service
    @_storage_provider_service ||= "StorageProvider::#{provider.to_s.capitalize}Provider".constantize.new
  end

  def default_environment_variables
    storage_provider_service.default_environment_variables
  end

  def required_environment_variables
    storage_provider_service.required_environment_variables
  end

  def validate_environment_variables
    required_environment_variables.each do |variable|
      errors.add(:environment_variable, "\"#{variable}\" is required") unless environment_variables[variable].present?
    end
  end
end

app/controllers/storage_providers_controller.rb
class StorageProvidersController < ApplicationController

  def index
    @providers = StorageProvider.all.order(created_at: :desc)
  end

  def choose
  end

  def new
    return redirect_to choose_storage_providers_path unless params[:provider].present?
    @provider = StorageProvider.new(provider: params[:provider])
  end

  def create
    @provider = StorageProvider.new(create_params)
    if @provider.save
      redirect_to storage_providers_path
    else
      render :new
    end
  end

  private

  def create_params
    provider_env_keys = StorageProvider.new(params.require(:storage_provider).permit(:provider)).default_environment_variables.keys
    params.require(:storage_provider).permit(:name, :provider, environment_variables: provider_env_keys)
  end

end

app/views/storage_providers/choose.html.haml
%h1.lead Choose A Provider

%table.table.table-striped.well
  %tr
    %th Service
    %th Create
  - StorageProvider::PROVIDERS.each do |provider|
    %tr
      %td= provider
      %td= link_to 'Create', new_storage_provider_path(provider: provider), class: 'btn btn-xs btn-primary'

app/views/storage_providers/index.html.haml
%h1.lead
  Storage Providers
  .pull-right
    = link_to '+', new_storage_provider_path, class: 'btn btn-success'

- if @providers.any?
  %table.table.table-striped
    %tr
      %th Name
      %th Provider
    - @providers.each do |provider|
      %tr
        %td= provider.name
        %td= provider.provider
- else
  %p.alert.alert-info You have not launched any services yet

app/views/storage_providers/new.html.haml
= content_for :title, "Create a #{@provider.provider.titleize} Storage Provider"

%h1.lead Create a #{@provider.provider.titleize} Storage Provider

= simple_form_for @provider do |f|

  = f.error_notification message: (f.object.errors.full_messages.join("<br />") )

  = f.input :name
  = f.input :provider, as: :hidden

  %h1.lead Environment Variables

  - environment_variables = ::EnvironmentVariablesDecorator.new(@provider.default_environment_variables.merge(@provider.environment_variables))
  = f.simple_fields_for(environment_variables) do |field|
    - environment_variables.each do |key, value|
      = field.input key, label: key.to_s

  = f.button :submit