config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: redirect('/services')

  resources :users, only: [:index, :new, :create, :destroy]
  resources :machines

  resources :storage_providers do
    collection do
      get :choose
    end
  end

  resources :services do
    resources :backups, only: [:create]

    collection do
      get :choose
    end
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      Container DB#{content_for?(:title) ? " - #{content_for(:title)}" : nil}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: "/"}
            Container DB
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li= link_to 'Services', services_path
            %li= link_to 'Machines', machines_path
            %li= link_to 'Users', users_path
            %li= link_to 'Storage Providers', storage_providers_path

          - if user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %ul.nav.navbar-nav.navbar-right
                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete

    .container
      - if flash[:info].present?
        %p.alert.alert-info= flash[:info]

      = yield